### ISSUE TITLE
Can you please update "illuminate/support" to support Laravel 11.

### ISSUE THREAD

**Issue by umuttaymaz** [highsidelabs/laravel-spapi#6]
<img width="776" alt="Screenshot 2024-04-08 at 03 50 44" src="https://github.com/highsidelabs/laravel-spapi/assets/7460205/4f3512ce-8675-4945-8ce1-e93f98007f9e">

Can you please update the package to support Laravel 11?

Thank you Jesse

**Comment by jlevers** [comment]
This is because `laravel-zero/framework`, which `highsidelabs/saloon-sdk-generator` requires, has not been upgraded to be compatible with Laravel 11. I think the right move here is to just figure out how to make `highsidelabs/saloon-sdk-generator` a dev dependency instead of a regular dependency, so that issues with dev packages don't effect regular users.

**Comment by jlevers** [comment]
Ah, Laravel 11 drops PHP 8.1 support, which this library supports. I'm going to have to cut a new major release for this, and I'd like to wait till I have this package upgraded to work with `jlevers/selling-partner-api` v6 to do that. I made a `2.x` dev branch that's Laravel 11 compatible which you can use in the meantime.

**Comment by shakethatweight-simon** [comment]
@jlevers  Do you still have plans to support jlevers/selling-partner-api v6? We've only recently started working with these 2 projects and would like to take advantage of some of the newer options. For example ExpiryDate on inbound shipments.

**Comment by jlevers** [comment]
`v2.x` now supports `jlevers/selling-partner-api` v7.
